CREATE SCHEMA IF NOT EXISTS usuarios AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS acervo AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS emprestimos AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS notificacoes AUTHORIZATION admin;
