spring.application.name=usuarios-ms
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/biblioteca?currentSchema=usuarios
spring.datasource.username=admin
spring.datasource.password=biblioteca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=usuarios

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=biblioteca

security.public-paths=/auth/login
security.jwt-secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes

microservice.emprestimos.url=localhost:8083

logging.level.br.edu.ifba.usuarios_ms.client=DEBUG
logging.level.feign=DEBUG