# ============================
# Identificação da aplicação
# ============================

# Nome do microsserviço
spring.application.name=notificacoes-ms

# Porta HTTP da aplicação
server.port=8084

# ============================
# RabbitMQ
# ============================

# Servidor RabbitMQ
spring.rabbitmq.host=localhost

# Porta AMQP
spring.rabbitmq.port=5672

# Credenciais RabbitMQ
spring.rabbitmq.username=admin
spring.rabbitmq.password=biblioteca

# ============================
# Comunicação entre microsserviços
# ============================

# URL do microsserviço de e-mail
microservice.email.url=http://localhost:8085

# ============================
# Configuração de E-mail
# ============================

# Destinatário das notificações
email.destinatario=${EMAIL_NOTIFICACAO_DESTINO}

# ============================
# Segurança JWT
# ============================

security.public-paths=/swagger-ui/**,/v3/api-docs/**
security.jwt-secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes
jwt.secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes

# ============================
# Variáveis de ambiente
# ============================

# Carrega o .env da raiz do projeto
spring.config.import=optional:file:../../.env[.properties]