# ============================
# Identificação da aplicação
# ============================

spring.application.name=gateway-ms
server.port=8080

# ============================
# Rotas do Gateway
# ============================

spring.cloud.gateway.server.webmvc.routes[0].id=usuarios
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/usuarios/**


spring.cloud.gateway.server.webmvc.routes[1].id=auth
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**


spring.cloud.gateway.server.webmvc.routes[2].id=acervo
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/livros/**


spring.cloud.gateway.server.webmvc.routes[3].id=emprestimos
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/emprestimos/**




logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.server.mvc=DEBUG
logging.level.org.springframework.web=DEBUG