# ============================
# Identificação da aplicação
# ============================

# Nome do microsserviço
spring.application.name=email-ms

# Porta HTTP da aplicação
server.port=8085


# ============================
# RabbitMQ
# ============================

# Servidor RabbitMQ
spring.rabbitmq.host=localhost

# Porta AMQP
spring.rabbitmq.port=5672

# Credenciais RabbitMQ
spring.rabbitmq.username=admin
spring.rabbitmq.password=biblioteca


# ============================
# SMTP (E-mail)
# ============================

# Servidor SMTP do Gmail
spring.mail.host=smtp.gmail.com

# Porta SMTP com STARTTLS
spring.mail.port=587

# Credenciais carregadas do .env
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

# Habilita autenticação SMTP
spring.mail.properties.mail.smtp.auth=true

# Habilita criptografia STARTTLS
spring.mail.properties.mail.smtp.starttls.enable=true


# ============================
# Variáveis de ambiente
# ============================

# Carrega o .env da raiz do projeto
spring.config.import=optional:file:../../.env[.properties]