spring.application.name=notificacoes-ms
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca?currentSchema=notificacoes
spring.datasource.username=admin
spring.datasource.password=biblioteca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=notificacoes

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=biblioteca

security.public-paths=/swagger-ui/**,/v3/api-docs/**
security.jwt-secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes
jwt.secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes