spring.application.name=notificacoes-ms
server.port=8084

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=biblioteca

security.public-paths=/swagger-ui/**,/v3/api-docs/**
security.jwt-secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes
jwt.secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes

microservice.email.url=http://localhost:8085
email.destinatario=${EMAIL_NOTIFICACAO_DESTINO}

spring.config.import=optional:file:../../.env[.properties]