# ============================
# Configuração do Gateway
# ============================

# Porta onde o Gateway será executado
server.port=8082

# Nome da aplicação Gateway dentro do ambiente Spring
spring.application.name=gateway

# ============================
# Configuração do Eureka Client
# ============================

# URL do Eureka Server utilizada para registrar e localizar serviços
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka/

# Faz com que o Gateway utilize seu endereço IP ao se registrar no Eureka
eureka.instance.prefer-ip-address=true

# ============================
# Localização automática de serviços
# ============================

# Permite que o Gateway localize automaticamente os serviços registrados no Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Permite usar o nome dos serviços em letras minúsculas nas URLs
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true