# ============================
# Identificação da aplicação
# ============================

# Nome da aplicação dentro do ambiente Spring
spring.application.name=email

# ============================
# Configuração do banco PostgreSQL
# ============================

# Endereço do banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Usuário do banco de dados
spring.datasource.username=${DB_USER}

# Senha do banco de dados
spring.datasource.password=${DB_PASSWORD}

# Driver JDBC usado para conexão com o PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================
# Configuração do Hibernate
# ============================

# Dialeto SQL usado pelo Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Atualiza automaticamente as tabelas conforme as entidades JPA
spring.jpa.hibernate.ddl-auto=update

# Exibe no console os comandos SQL executados
spring.jpa.show-sql=true