# ============================
# Identificação da aplicação
# ============================

# Nome do microsserviço
spring.application.name=gateway-ms

# Porta HTTP da aplicação
server.port=8080

# ============================
# Rotas do Gateway
# ============================

# Rota para o microsserviço de usuários
spring.cloud.gateway.server.webmvc.routes[0].id=usuarios
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/usuarios/**

# Rota para o microsserviço de acervo
spring.cloud.gateway.server.webmvc.routes[1].id=acervo
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/livros/**

# Rota para o microsserviço de empréstimos
spring.cloud.gateway.server.webmvc.routes[2].id=emprestimos
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/emprestimos/**

# ============================
# Logs do Spring Cloud Gateway
# ============================

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.server.mvc=DEBUG
logging.level.org.springframework.web=DEBUG