# ============================
# Identificação da aplicação
# ============================

# Nome do microsserviço
spring.application.name=acervo-ms

# Porta HTTP da aplicação
server.port=8082


# ============================
# Banco de dados PostgreSQL
# ============================

# URL de conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5433/biblioteca?currentSchema=acervo

# Credenciais do banco
spring.datasource.username=admin
spring.datasource.password=biblioteca

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver


# ============================
# JPA / Hibernate
# ============================

# Atualiza automaticamente o schema conforme as entidades
spring.jpa.hibernate.ddl-auto=update

# Exibe SQL gerado pelo Hibernate
spring.jpa.show-sql=true

# Formata os comandos SQL exibidos no console
spring.jpa.properties.hibernate.format_sql=true

# Schema padrão utilizado pelo Hibernate
spring.jpa.properties.hibernate.default_schema=acervo


# ============================
# RabbitMQ
# ============================

# Servidor RabbitMQ
spring.rabbitmq.host=localhost

# Porta AMQP
spring.rabbitmq.port=5672

# Credenciais RabbitMQ
spring.rabbitmq.username=admin
spring.rabbitmq.password=biblioteca


# ============================
# Comunicação entre microsserviços
# ============================

# URL do microsserviço de empréstimos
services.emprestimos.url=http://localhost:8083


# ============================
# Segurança JWT (temporariamente desabilitada)
# ============================

#security.public-paths=/livros
security.jwt-secret=minha-chave-secreta-super-protegida-com-mais-de-trinta-e-dois-bytes


# ============================
# Logs Spring Security
# ============================

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE